[app]
id = "w3spayadmin.dot"
name = "W3sPay Admin"
version = "0.1.0"
app_type = "spa"

[webapp]
entry = "index.html"
sandbox = "strict"

[extensions]
use_extensions = ["host.data", "host.browser.bridge", "host.api", "host.media"]
