// SPDX-License-Identifier: GPL-3.0-or-later
// @paritytech

export const W3SPayRegistryABI = [
  {
    inputs: [],
    name: "getVersion",
    outputs: [{ internalType: "uint64", name: "", type: "uint64" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getMerchantCount",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getAllTerminalKeys",
    outputs: [{ internalType: "bytes32[]", name: "", type: "bytes32[]" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32", name: "key", type: "bytes32" }],
    name: "getMerchantByKey",
    outputs: [
      {
        components: [
          { internalType: "string", name: "merchantId", type: "string" },
          { internalType: "string", name: "terminalId", type: "string" },
          { internalType: "bytes32", name: "destinationAccountId", type: "bytes32" },
          { internalType: "string", name: "displayName", type: "string" },
          { internalType: "enum IW3SPayRegistry.MerchantStatus", name: "status", type: "uint8" },
          { internalType: "uint64", name: "addedAt", type: "uint64" },
          { internalType: "uint64", name: "updatedAt", type: "uint64" },
          { internalType: "bool", name: "exists", type: "bool" },
        ],
        internalType: "struct IW3SPayRegistry.MerchantEntry",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "string", name: "merchantId", type: "string" },
      { internalType: "string", name: "terminalId", type: "string" },
    ],
    name: "getMerchant",
    outputs: [
      {
        components: [
          { internalType: "string", name: "merchantId", type: "string" },
          { internalType: "string", name: "terminalId", type: "string" },
          { internalType: "bytes32", name: "destinationAccountId", type: "bytes32" },
          { internalType: "string", name: "displayName", type: "string" },
          { internalType: "enum IW3SPayRegistry.MerchantStatus", name: "status", type: "uint8" },
          { internalType: "uint64", name: "addedAt", type: "uint64" },
          { internalType: "uint64", name: "updatedAt", type: "uint64" },
          { internalType: "bool", name: "exists", type: "bool" },
        ],
        internalType: "struct IW3SPayRegistry.MerchantEntry",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "who", type: "address" }],
    name: "isAdmin",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "string", name: "merchantId", type: "string" },
      { internalType: "string", name: "terminalId", type: "string" },
      { internalType: "bytes32", name: "destinationAccountId", type: "bytes32" },
      { internalType: "string", name: "displayName", type: "string" },
    ],
    name: "registerMerchant",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "string", name: "merchantId", type: "string" },
      { internalType: "string", name: "terminalId", type: "string" },
      { internalType: "bytes32", name: "destinationAccountId", type: "bytes32" },
      { internalType: "string", name: "displayName", type: "string" },
    ],
    name: "updateMerchant",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "string", name: "merchantId", type: "string" },
      { internalType: "string", name: "terminalId", type: "string" },
      { internalType: "bytes32", name: "destinationAccountId", type: "bytes32" },
    ],
    name: "setMerchantDestination",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "string", name: "merchantId", type: "string" },
      { internalType: "string", name: "terminalId", type: "string" },
      { internalType: "enum IW3SPayRegistry.MerchantStatus", name: "status", type: "uint8" },
    ],
    name: "setMerchantStatus",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "string", name: "merchantId", type: "string" },
      { internalType: "string", name: "terminalId", type: "string" },
    ],
    name: "removeMerchant",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "string", name: "configId", type: "string" },
      { internalType: "string", name: "cid", type: "string" },
      { internalType: "uint32", name: "size", type: "uint32" },
    ],
    name: "upsertItemConfig",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "string", name: "configId", type: "string" }],
    name: "removeItemConfig",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "string", name: "configId", type: "string" }],
    name: "getItemConfig",
    outputs: [
      {
        components: [
          { internalType: "string", name: "configId", type: "string" },
          { internalType: "string", name: "cid", type: "string" },
          { internalType: "uint32", name: "size", type: "uint32" },
          { internalType: "uint64", name: "updatedAt", type: "uint64" },
          { internalType: "bool", name: "exists", type: "bool" },
        ],
        internalType: "struct IW3SPayRegistry.ItemConfigRecord",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getAllItemConfigIds",
    outputs: [{ internalType: "string[]", name: "", type: "string[]" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getItemConfigCount",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "string", name: "groupId", type: "string" },
      { internalType: "string", name: "cid", type: "string" },
      { internalType: "uint32", name: "size", type: "uint32" },
    ],
    name: "upsertProcessorConfig",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "string", name: "groupId", type: "string" }],
    name: "removeProcessorConfig",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "string", name: "groupId", type: "string" }],
    name: "getProcessorConfig",
    outputs: [
      {
        components: [
          { internalType: "string", name: "groupId", type: "string" },
          { internalType: "string", name: "cid", type: "string" },
          { internalType: "uint32", name: "size", type: "uint32" },
          { internalType: "uint64", name: "updatedAt", type: "uint64" },
          { internalType: "bool", name: "exists", type: "bool" },
        ],
        internalType: "struct IW3SPayRegistry.ProcessorConfigRecord",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getAllProcessorConfigIds",
    outputs: [{ internalType: "string[]", name: "", type: "string[]" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getProcessorConfigCount",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "string", name: "groupId", type: "string" },
      { internalType: "string", name: "merchantName", type: "string" },
      { internalType: "string", name: "merchantId", type: "string" },
      { internalType: "string", name: "addressLine1", type: "string" },
      { internalType: "string", name: "addressLine2", type: "string" },
      { internalType: "string", name: "phone", type: "string" },
      { internalType: "string", name: "taxId", type: "string" },
    ],
    name: "upsertMerchantProfile",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "string", name: "groupId", type: "string" }],
    name: "removeMerchantProfile",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "string", name: "groupId", type: "string" }],
    name: "getMerchantProfile",
    outputs: [
      {
        components: [
          { internalType: "string", name: "groupId", type: "string" },
          { internalType: "string", name: "merchantName", type: "string" },
          { internalType: "string", name: "merchantId", type: "string" },
          { internalType: "string", name: "addressLine1", type: "string" },
          { internalType: "string", name: "addressLine2", type: "string" },
          { internalType: "string", name: "phone", type: "string" },
          { internalType: "string", name: "taxId", type: "string" },
          { internalType: "uint64", name: "updatedAt", type: "uint64" },
          { internalType: "bool", name: "exists", type: "bool" },
        ],
        internalType: "struct IW3SPayRegistry.MerchantProfile",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getAllMerchantProfileIds",
    outputs: [{ internalType: "string[]", name: "", type: "string[]" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getMerchantProfileCount",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "string", name: "groupId", type: "string" },
      { internalType: "uint64", name: "seq", type: "uint64" },
      { internalType: "string", name: "cid", type: "string" },
      { internalType: "uint32", name: "size", type: "uint32" },
    ],
    name: "addProcessorReport",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "string", name: "groupId", type: "string" },
      { internalType: "uint64", name: "seq", type: "uint64" },
    ],
    name: "getProcessorReport",
    outputs: [
      {
        components: [
          { internalType: "uint64", name: "seq", type: "uint64" },
          { internalType: "string", name: "cid", type: "string" },
          { internalType: "uint32", name: "size", type: "uint32" },
          { internalType: "uint64", name: "committedAt", type: "uint64" },
          { internalType: "bool", name: "exists", type: "bool" },
        ],
        internalType: "struct IW3SPayRegistry.ProcessorReportRecord",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "string", name: "groupId", type: "string" }],
    name: "getProcessorReportSeqs",
    outputs: [{ internalType: "uint64[]", name: "", type: "uint64[]" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "string", name: "groupId", type: "string" }],
    name: "getProcessorReportCount",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address[]", name: "newAdmins", type: "address[]" }],
    name: "bulkAddAdmins",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "who", type: "address" }],
    name: "isSuperAdmin",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "admin", type: "address" }],
    name: "addAdmin",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "admin", type: "address" }],
    name: "removeAdmin",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "account", type: "address" }],
    name: "addSuperAdmin",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "account", type: "address" }],
    name: "removeSuperAdmin",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;
