export const W3SPayMerchantRegistryABI = [
  {
    inputs: [],
    name: "getVersion",
    outputs: [{ internalType: "uint64", name: "", type: "uint64" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getMerchantCount",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getAllTerminalKeys",
    outputs: [{ internalType: "bytes32[]", name: "", type: "bytes32[]" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32", name: "key", type: "bytes32" }],
    name: "getMerchantByKey",
    outputs: [
      {
        components: [
          { internalType: "string", name: "merchantId", type: "string" },
          { internalType: "string", name: "terminalId", type: "string" },
          { internalType: "bytes32", name: "destinationAccountId", type: "bytes32" },
          { internalType: "string", name: "displayName", type: "string" },
          { internalType: "enum IW3SPayMerchantRegistry.MerchantStatus", name: "status", type: "uint8" },
          { internalType: "uint64", name: "addedAt", type: "uint64" },
          { internalType: "uint64", name: "updatedAt", type: "uint64" },
          { internalType: "bool", name: "exists", type: "bool" },
        ],
        internalType: "struct IW3SPayMerchantRegistry.MerchantEntry",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "string", name: "merchantId", type: "string" },
      { internalType: "string", name: "terminalId", type: "string" },
    ],
    name: "getMerchant",
    outputs: [
      {
        components: [
          { internalType: "string", name: "merchantId", type: "string" },
          { internalType: "string", name: "terminalId", type: "string" },
          { internalType: "bytes32", name: "destinationAccountId", type: "bytes32" },
          { internalType: "string", name: "displayName", type: "string" },
          { internalType: "enum IW3SPayMerchantRegistry.MerchantStatus", name: "status", type: "uint8" },
          { internalType: "uint64", name: "addedAt", type: "uint64" },
          { internalType: "uint64", name: "updatedAt", type: "uint64" },
          { internalType: "bool", name: "exists", type: "bool" },
        ],
        internalType: "struct IW3SPayMerchantRegistry.MerchantEntry",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "who", type: "address" }],
    name: "isAdmin",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "string", name: "merchantId", type: "string" },
      { internalType: "string", name: "terminalId", type: "string" },
      { internalType: "bytes32", name: "destinationAccountId", type: "bytes32" },
      { internalType: "string", name: "displayName", type: "string" },
    ],
    name: "registerMerchant",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "string", name: "merchantId", type: "string" },
      { internalType: "string", name: "terminalId", type: "string" },
      { internalType: "bytes32", name: "destinationAccountId", type: "bytes32" },
      { internalType: "string", name: "displayName", type: "string" },
    ],
    name: "updateMerchant",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "string", name: "merchantId", type: "string" },
      { internalType: "string", name: "terminalId", type: "string" },
      { internalType: "bytes32", name: "destinationAccountId", type: "bytes32" },
    ],
    name: "setMerchantDestination",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "string", name: "merchantId", type: "string" },
      { internalType: "string", name: "terminalId", type: "string" },
      { internalType: "enum IW3SPayMerchantRegistry.MerchantStatus", name: "status", type: "uint8" },
    ],
    name: "setMerchantStatus",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "string", name: "merchantId", type: "string" },
      { internalType: "string", name: "terminalId", type: "string" },
    ],
    name: "removeMerchant",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "string", name: "configId", type: "string" },
      { internalType: "string", name: "cid", type: "string" },
      { internalType: "uint32", name: "size", type: "uint32" },
    ],
    name: "upsertItemConfig",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "string", name: "configId", type: "string" }],
    name: "removeItemConfig",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "string", name: "configId", type: "string" }],
    name: "getItemConfig",
    outputs: [
      {
        components: [
          { internalType: "string", name: "configId", type: "string" },
          { internalType: "string", name: "cid", type: "string" },
          { internalType: "uint32", name: "size", type: "uint32" },
          { internalType: "uint64", name: "updatedAt", type: "uint64" },
          { internalType: "bool", name: "exists", type: "bool" },
        ],
        internalType: "struct IW3SPayMerchantRegistry.ItemConfigRecord",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getAllItemConfigIds",
    outputs: [{ internalType: "string[]", name: "", type: "string[]" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getItemConfigCount",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
] as const;
